/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Content.PackInv.View;

import Content.PackInv.View.*;
import Content.PackInv.Controller.ExecuteActionController;
import Content.PackInv.Model.InvDataModels;
import Content.PackInv.Model.InvTableDisplay;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author MakkaH-73
 */
public class ViewSInvJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewSInvJFrame
     */
    public ViewSInvJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salesInvTableDisplay = new javax.swing.JTable();
        salesInvTableDisplay.getSelectionModel().addListSelectionListener(executeActionController);
        createNewInvoiceBTN = new javax.swing.JButton();
        createNewInvoiceBTN.addActionListener(executeActionController);
        deleteInvoiceBTN = new javax.swing.JButton();
        deleteInvoiceBTN.addActionListener(executeActionController);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invNumLabel1 = new javax.swing.JLabel();
        invDateLabel2 = new javax.swing.JLabel();
        invCusNameLabel3 = new javax.swing.JLabel();
        invTotalLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesInvItemInfo = new javax.swing.JTable();
        createInvoiceItemBTN = new javax.swing.JButton();
        createInvoiceItemBTN.addActionListener(executeActionController);
        deleteInvoiceItemBTN = new javax.swing.JButton();
        deleteInvoiceItemBTN.addActionListener(executeActionController);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadingMenuItemFile = new javax.swing.JMenuItem();
        loadingMenuItemFile.addActionListener(executeActionController);
        savingMenuItemFile = new javax.swing.JMenuItem();
        savingMenuItemFile.addActionListener(executeActionController);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salesInvTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(salesInvTableDisplay);

        createNewInvoiceBTN.setText("Create New Invoice");

        deleteInvoiceBTN.setText("Delete Invoice ");
        deleteInvoiceBTN.setActionCommand("Delete Invoice");
        deleteInvoiceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvoiceBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Invoice Date");

        jLabel3.setText("Customer Name");

        jLabel4.setText("Invoice Total");

        invNumLabel1.setText("0");

        invDateLabel2.setText("0");

        invCusNameLabel3.setText("0");

        invTotalLabel4.setText("0");

        salesInvItemInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(salesInvItemInfo);

        createInvoiceItemBTN.setText("Create New Item");

        deleteInvoiceItemBTN.setText("Delete Item");

        jMenu1.setText("File");

        loadingMenuItemFile.setText("Load File");
        loadingMenuItemFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadingMenuItemFileActionPerformed(evt);
            }
        });
        jMenu1.add(loadingMenuItemFile);

        savingMenuItemFile.setText("Save File");
        jMenu1.add(savingMenuItemFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(createNewInvoiceBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInvoiceBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createInvoiceItemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInvoiceItemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invDateLabel2)
                                    .addComponent(invNumLabel1)
                                    .addComponent(invCusNameLabel3)
                                    .addComponent(invTotalLabel4)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invNumLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invDateLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invCusNameLabel3)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(invTotalLabel4))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewInvoiceBTN)
                    .addComponent(deleteInvoiceBTN)
                    .addComponent(deleteInvoiceItemBTN)
                    .addComponent(createInvoiceItemBTN))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadingMenuItemFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadingMenuItemFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadingMenuItemFileActionPerformed

    private void deleteInvoiceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInvoiceBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSInvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSInvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSInvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSInvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSInvJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createInvoiceItemBTN;
    private javax.swing.JButton createNewInvoiceBTN;
    private javax.swing.JButton deleteInvoiceBTN;
    private javax.swing.JButton deleteInvoiceItemBTN;
    private javax.swing.JLabel invCusNameLabel3;
    private javax.swing.JLabel invDateLabel2;
    private javax.swing.JLabel invNumLabel1;
    private javax.swing.JLabel invTotalLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadingMenuItemFile;
    private javax.swing.JTable salesInvItemInfo;
    private javax.swing.JTable salesInvTableDisplay;
    private javax.swing.JMenuItem savingMenuItemFile;
    // End of variables declaration//GEN-END:variables

    private ArrayList<InvDataModels> invData ;    
    
        private ExecuteActionController executeActionController = new ExecuteActionController(this); 

         private InvTableDisplay invTableDisplay;
         
         
         
         public ArrayList<InvDataModels> getInvData() {
        if (invData == null) invData = new ArrayList<>();
        return invData;
    }

         
         public void setInvData(ArrayList<InvDataModels> invData) {
        this.invData = invData;
    }
         
         
         
    public InvTableDisplay getInvTableDisplay() {
        if (invTableDisplay == null) {
            invTableDisplay = new InvTableDisplay(getInvData());
        }
        return invTableDisplay;
    }
    
    
   

    public void setInvTableDisplay(InvTableDisplay invTableDisplay) {
        this.invTableDisplay = invTableDisplay;
    }

    
    
    
    
    public JLabel getInvCusNameLabel3() {
        return invCusNameLabel3;
    }

    public JLabel getInvDateLabel2() {
        return invDateLabel2;
    }

    public JLabel getInvNumLabel1() {
        return invNumLabel1;
    }

    public JLabel getInvTotalLabel4() {
        return invTotalLabel4;
    }

    public JTable getSalesInvItemInfo() {
        return salesInvItemInfo;
    }

    public JTable getSalesInvTableDisplay() {
        return salesInvTableDisplay;
    }
    
    

    public ExecuteActionController getExecuteActionController() {
        return executeActionController;
    }
    
    
    public int getNextInvNumber() {
        int number = 0;
        
        for (InvDataModels invDataModels : invData) {
            if (invDataModels.getNumberOfCustomer() > number) 
                number = invDataModels.getNumberOfCustomer();
        }
        
        return ++number;
    }
    
    
    
    
    
    
}
